<!DOCTYPE html>
<html xmlns="http://www.w3.org/1999/xhtml" lang="en" xml:lang="en"><head>

<meta charset="utf-8">
<meta name="generator" content="quarto-1.4.553">

<meta name="viewport" content="width=device-width, initial-scale=1.0, user-scalable=yes">

<meta name="author" content="Vanshika Vanshika">
<meta name="author" content="Navya Hooda">
<meta name="author" content="Shea Munson">
<meta name="author" content="Alexia Mbagaya">
<meta name="author" content="Chloe Syriac">
<meta name="dcterms.date" content="2024-11-28">

<title>Various Demographic Factors Effect on Students’ Participation In Extracurricular Activities</title>
<style>
code{white-space: pre-wrap;}
span.smallcaps{font-variant: small-caps;}
div.columns{display: flex; gap: min(4vw, 1.5em);}
div.column{flex: auto; overflow-x: auto;}
div.hanging-indent{margin-left: 1.5em; text-indent: -1.5em;}
ul.task-list{list-style: none;}
ul.task-list li input[type="checkbox"] {
  width: 0.8em;
  margin: 0 0.8em 0.2em -1em; /* quarto-specific, see https://github.com/quarto-dev/quarto-cli/issues/4556 */ 
  vertical-align: middle;
}
</style>


<script src="technical_report_files/libs/clipboard/clipboard.min.js"></script>
<script src="technical_report_files/libs/quarto-html/quarto.js"></script>
<script src="technical_report_files/libs/quarto-html/popper.min.js"></script>
<script src="technical_report_files/libs/quarto-html/tippy.umd.min.js"></script>
<script src="technical_report_files/libs/quarto-html/anchor.min.js"></script>
<link href="technical_report_files/libs/quarto-html/tippy.css" rel="stylesheet">
<link href="technical_report_files/libs/quarto-html/quarto-syntax-highlighting.css" rel="stylesheet" id="quarto-text-highlighting-styles">
<script src="technical_report_files/libs/bootstrap/bootstrap.min.js"></script>
<link href="technical_report_files/libs/bootstrap/bootstrap-icons.css" rel="stylesheet">
<link href="technical_report_files/libs/bootstrap/bootstrap.min.css" rel="stylesheet" id="quarto-bootstrap" data-mode="light">
</head><body>\usepackage{amsmath}
\usepackage{amssymb}
\usepackage{pgfplots}

  <script src="https://polyfill.io/v3/polyfill.min.js?features=es6"></script>
  <script src="https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-chtml-full.js" type="text/javascript"></script>

<script type="text/javascript">
const typesetMath = (el) => {
  if (window.MathJax) {
    // MathJax Typeset
    window.MathJax.typeset([el]);
  } else if (window.katex) {
    // KaTeX Render
    var mathElements = el.getElementsByClassName("math");
    var macros = [];
    for (var i = 0; i < mathElements.length; i++) {
      var texText = mathElements[i].firstChild;
      if (mathElements[i].tagName == "SPAN") {
        window.katex.render(texText.data, mathElements[i], {
          displayMode: mathElements[i].classList.contains('display'),
          throwOnError: false,
          macros: macros,
          fleqn: false
        });
      }
    }
  }
}
window.Quarto = {
  typesetMath
};
</script>





<div id="quarto-content" class="page-columns page-rows-contents page-layout-article">
<div id="quarto-margin-sidebar" class="sidebar margin-sidebar">
  <nav id="TOC" role="doc-toc" class="toc-active">
    <h2 id="toc-title">Table of contents</h2>
   
  <ul>
  <li><a href="#introduction" id="toc-introduction" class="nav-link active" data-scroll-target="#introduction"><span class="header-section-number">1</span> Introduction</a>
  <ul class="collapse">
  <li><a href="#research-questions-and-hypotheses" id="toc-research-questions-and-hypotheses" class="nav-link" data-scroll-target="#research-questions-and-hypotheses"><span class="header-section-number">1.1</span> Research Questions and Hypotheses</a></li>
  </ul></li>
  <li><a href="#sec-data" id="toc-sec-data" class="nav-link" data-scroll-target="#sec-data"><span class="header-section-number">2</span> Data</a>
  <ul class="collapse">
  <li><a href="#methodology" id="toc-methodology" class="nav-link" data-scroll-target="#methodology"><span class="header-section-number">2.1</span> Methodology</a></li>
  </ul></li>
  <li><a href="#sec-data1" id="toc-sec-data1" class="nav-link" data-scroll-target="#sec-data1"><span class="header-section-number">3</span> Analysis</a>
  <ul class="collapse">
  <li><a href="#research-question-1" id="toc-research-question-1" class="nav-link" data-scroll-target="#research-question-1"><span class="header-section-number">3.1</span> Research Question 1</a>
  <ul class="collapse">
  <li><a href="#testing-for-the-significance-of-majors-on-activity-proportion-using-the-anova-test" id="toc-testing-for-the-significance-of-majors-on-activity-proportion-using-the-anova-test" class="nav-link" data-scroll-target="#testing-for-the-significance-of-majors-on-activity-proportion-using-the-anova-test"><span class="header-section-number">3.1.1</span> Testing for the Significance of Majors on Activity Proportion using the ANOVA Test</a></li>
  <li><a href="#testing-for-the-significance-of-gender-on-activity-proportion-using-the-t-test" id="toc-testing-for-the-significance-of-gender-on-activity-proportion-using-the-t-test" class="nav-link" data-scroll-target="#testing-for-the-significance-of-gender-on-activity-proportion-using-the-t-test"><span class="header-section-number">3.1.2</span> Testing for the Significance of Gender on Activity Proportion using the T-Test</a></li>
  <li><a href="#testing-for-the-significance-of-student-status-on-activity-proportion-using-the-t-test" id="toc-testing-for-the-significance-of-student-status-on-activity-proportion-using-the-t-test" class="nav-link" data-scroll-target="#testing-for-the-significance-of-student-status-on-activity-proportion-using-the-t-test"><span class="header-section-number">3.1.3</span> Testing for the Significance of Student Status on Activity Proportion using the T-Test</a></li>
  </ul></li>
  <li><a href="#research-question-2" id="toc-research-question-2" class="nav-link" data-scroll-target="#research-question-2"><span class="header-section-number">3.2</span> Research Question 2</a>
  <ul class="collapse">
  <li><a href="#campus-distance-and-activity-count" id="toc-campus-distance-and-activity-count" class="nav-link" data-scroll-target="#campus-distance-and-activity-count"><span class="header-section-number">3.2.1</span> Campus Distance and Activity Count</a></li>
  </ul></li>
  <li><a href="#research-question-3" id="toc-research-question-3" class="nav-link" data-scroll-target="#research-question-3"><span class="header-section-number">3.3</span> Research Question 3</a>
  <ul class="collapse">
  <li><a href="#time-commitment-and-student-involvement" id="toc-time-commitment-and-student-involvement" class="nav-link" data-scroll-target="#time-commitment-and-student-involvement"><span class="header-section-number">3.3.1</span> Time Commitment and Student Involvement</a></li>
  <li><a href="#time-commitment-and-activity-count" id="toc-time-commitment-and-activity-count" class="nav-link" data-scroll-target="#time-commitment-and-activity-count"><span class="header-section-number">3.3.2</span> Time Commitment and Activity Count</a></li>
  </ul></li>
  </ul></li>
  <li><a href="#sec-data3" id="toc-sec-data3" class="nav-link" data-scroll-target="#sec-data3"><span class="header-section-number">4</span> Limitations</a></li>
  <li><a href="#conclusion" id="toc-conclusion" class="nav-link" data-scroll-target="#conclusion"><span class="header-section-number">5</span> Conclusion</a></li>
  <li><a href="#references" id="toc-references" class="nav-link" data-scroll-target="#references"><span class="header-section-number">6</span> References</a></li>
  </ul>
</nav>
</div>
<main class="content" id="quarto-document-content">

<header id="title-block-header" class="quarto-title-block default">
<div class="quarto-title">
<h1 class="title">Various Demographic Factors Effect on Students’ Participation In Extracurricular Activities</h1>
<p class="subtitle lead">Data Collected from STA304H5F in 2024</p>
</div>



<div class="quarto-title-meta">

    <div>
    <div class="quarto-title-meta-heading">Authors</div>
    <div class="quarto-title-meta-contents">
             <p>Vanshika Vanshika </p>
             <p>Navya Hooda </p>
             <p>Shea Munson </p>
             <p>Alexia Mbagaya </p>
             <p>Chloe Syriac </p>
          </div>
  </div>
    
    <div>
    <div class="quarto-title-meta-heading">Published</div>
    <div class="quarto-title-meta-contents">
      <p class="date">November 28, 2024</p>
    </div>
  </div>
  
    
  </div>
  
<div>
  <div class="abstract">
    <div class="block-title">Abstract</div>
    It is known that for students to have a well-rounded university experience, participation in extracurricular activities is vital, not only for academic but personal growth. However, student participation in extracurricular activities depends on a number of factors. Some include scheduling and time-commitment factors, commute factors and the diversity of student activities/clubs. This study aims to explore this by investigating the reasons that students select certain extracurricular activities at the University of Toronto Mississauga (UTM) campus. An anonymous online survey on Google Forms was created for students in a third-year Statistics course to complete. Findings showed that there was no significant relationship between campus distance and program of study with extracurricular involvement. Although there was some gender influence on the participation of extra-curricular activity, this variation is not statistically relevant as the p-value was 1. On the other hand, there was a statistically significant monotonic relationship (rho = 0.937) between time commitment and activity count. As students increase their time commitment, so does their participation in ECAs. Although results produced minimal significant findings, we believe that this is a valiant step in the right direction towards investigating student participation at UTM.
  </div>
</div>


</header>


<section id="introduction" class="level1" data-number="1">
<h1 data-number="1"><span class="header-section-number">1</span> Introduction</h1>
<p>An important part of having a healthy life in university is maintaining a balance between school, work, and social life. Among other aspects, a major part of many university students’ social lives is extracurricular activities (ECAs). Being such a major part of students’ social lives, determining what factors can negatively impact student participation in ECAs is a critical step in helping minimize negative impacts on students’ wellbeing. In our study, we focused on students in STA304 students in Fall of 2024 and examined their levels of participation in various kinds of ECA’s. In particular, we analyzed if various demographic factors affected students’ participation in ECAs. As UTM is primarily a commuter campus, of special interest was students living distance from campus. To conduct our study, during the first three weeks of October 2024 we distributed a survey on the STA304 Piazza Discussion board to collect data on student demographics factors and information relating to individual participation in ECAs. Our study consisted of three research questions.</p>
<section id="research-questions-and-hypotheses" class="level2" data-number="1.1">
<h2 data-number="1.1" class="anchored" data-anchor-id="research-questions-and-hypotheses"><span class="header-section-number">1.1</span> Research Questions and Hypotheses</h2>
<ol type="1">
<li><strong>Research Question 1</strong>: What is the most preferred type of extracurricular activity, and do demographic factors influence student preferences for certain extracurricular activities?
<ul>
<li><span class="math inline">\(H_{0}\)</span>: Student demographic factors have no effect on participation in extracurricular activities.</li>
<li><span class="math inline">\(H_{a}\)</span>: Participation in extracurricular activities is affected by demographic factors.</li>
</ul></li>
<li><strong>Research Question 2</strong>: Does proximity to campus affect participation in extracurricular activities?
<ul>
<li><span class="math inline">\(H_{0}\)</span>: Proximity to campus has no effect on participation in extracurricular activities.</li>
<li><span class="math inline">\(H_{a}\)</span>: Students living further from campus will have lower participation rates.</li>
</ul></li>
<li><strong>Research Question 3</strong>: Does timing/scheduling of extracurricular activities impact student participation in extracurricular activities?
<ul>
<li><span class="math inline">\(H_{0}\)</span>: Timing/scheduling of extracurricular activities has no impact on student participation.</li>
<li><span class="math inline">\(H_{a}\)</span>: Participation in extracurricular activities is affected by their timing/scheduling.</li>
</ul></li>
</ol>
</section>
</section>
<section id="sec-data" class="level1" data-number="2">
<h1 data-number="2"><span class="header-section-number">2</span> Data</h1>
<section id="methodology" class="level2" data-number="2.1">
<h2 data-number="2.1" class="anchored" data-anchor-id="methodology"><span class="header-section-number">2.1</span> Methodology</h2>
<p>Data collection began in the first three weeks of October 2024, an online anonymous survey on Google Forms was created for participants to complete. This survey was created in order to investigate the reasons that students select and participate in certain ECAs. This online survey was posted to a Piazza thread where students can easily locate the survey link. Although using Stratified Random Sampling where the strata were the STA304 lecture sections (ie. LEC0101 and LEC0102) was proposed, the sampling method that was truly used was Simple random sampling. Nevertheless, randomness was ensured as the link to the survey was posted to Piazza where everyone had the equal opportunity to complete the survey and be chosen for the study. We collected a sample of 63 students. The survey consisted of 10 questions asking for details on their lecture section, demographic information, program of study, and distance from the UTM campus. We also included questions on the number, types of activities and the time commitment of the ECAs they are involved in. To encourage students to complete our online survey, we asked participants to share a link to their group’s survey, which we would complete in return.</p>
<p>For computing the sample size from population size of <span class="math inline">\(N = 200\)</span>, we chose a bound of <span class="math inline">\(B = 0.1047\)</span> and calculated with an approximation of <span class="math inline">\(p = 0.5\)</span>. Calculating a sample size using <span class="math inline">\(n = \frac{Npq}{(N-1)\frac{B^2}{4}+pq}\)</span> gives <span class="math inline">\(\frac{200*0.25*0.25}{(200-1)*\frac{0.1047^2}{4}+0.25} = 62.8643 \approx 63\)</span></p>
</section>
</section>
<section id="sec-data1" class="level1" data-number="3">
<h1 data-number="3"><span class="header-section-number">3</span> Analysis</h1>
<p>The majority of the analysis for our research questions is based on the various student demographic factors. As such, it is worthwhile to go over, in a preliminary fashion, the results of our survey to give further background on the study before continuing into the analysis of the research questions.</p>
<p>We had a slightly higher response rate from students in LEC0101, approximately a 6:4 ratio.</p>
<div class="cell" data-tbl-cap="Correlation Analysis">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/p1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Our sample indicated a higher percentage of males vs females, with no students responding with Other or Prefer Not to Answer</p>
<div class="cell" data-tbl-cap="Correlation Analysis">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/p2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Students picked up to 2 majors, with STA seeing a significant share of responses.</p>
<div class="cell" data-tbl-cap="Correlation Analysis">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/p3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>We had almost an even balance of Domestic and International students in our responses.</p>
<div class="cell" data-tbl-cap="Correlation Analysis">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/p4-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>Finally, we recorded students living distance from campus.</p>
<div class="cell" data-tbl-cap="Correlation Analysis">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/p5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<section id="research-question-1" class="level2" data-number="3.1">
<h2 data-number="3.1" class="anchored" data-anchor-id="research-question-1"><span class="header-section-number">3.1</span> Research Question 1</h2>
<p>In this question we aimed to explore and find out which is the most preferred types of extracurricular activities whilst also examining whether demographic factors such as major, demographics and student status influence the preference for certain extracurricular activities. By conducting this analysis we hope to gain an understanding of the sample and the wider population in their extracurricular selection habits.</p>
<p><strong>NOTE:</strong> For easy analysis and ability to come up with clearer conclusions, the Major column and the activity column were split into different rows.</p>
<p>For the most preferred type of extracurricular activity, we were able to get the count of students in the different extracurricular activities and display a graph showing the counts of students in each extracurricular activity.</p>
<div class="cell" data-tbl-cap="Count of Students by Activity Type">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/rq1-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>According to the bar plot, the most popular extracurricular activity among students was Athletics and Sports (AAS) with 42 students and the least popular extracurricular activity is Academic Societies (ACS) with 9 students. It was also particularly interesting to observe that most students do not participate in Extracurricular Activities, making the NEC category second in popularity.</p>
<p>To investigate the proportion of students participating in each activity by demographic factors like Major, Student Status and Gender Identity, we used two statistical tests, namely ANOVA and the T-Test.</p>
<p>Before we began with our tests we first conducted preliminary assumption tests.</p>
<section id="testing-for-the-significance-of-majors-on-activity-proportion-using-the-anova-test" class="level3" data-number="3.1.1">
<h3 data-number="3.1.1" class="anchored" data-anchor-id="testing-for-the-significance-of-majors-on-activity-proportion-using-the-anova-test"><span class="header-section-number">3.1.1</span> Testing for the Significance of Majors on Activity Proportion using the ANOVA Test</h3>
<p>The Assumptions of ANOVA are:</p>
<ol type="1">
<li>Normality: The data within each group should be normally distributed</li>
<li>Homogeneity of Variances: The variance of data within each group should be equal.</li>
<li>Random Sampling: Observations from each group have been sampled randomly and are independent of each other. (When we were collecting our sample this was already put into account)</li>
</ol>
<p>To test for Normality we used a Q-Q residuals plot.</p>
<div class="cell" data-tbl-cap="Q-Q Residuals Plot">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/r2-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>From the plot we can observe that the points almost follow a straight a line indicating that the residuals are normally distributed.</p>
<p>To test the equality of variances within each group we used the Levene Test.</p>
<p><strong><em>Null Hypothesis</em></strong> (<span class="math inline">\(H_{o}\)</span>) : The population variances between the groups are equal.</p>
<p><strong><em>Alternative Hypothesis</em></strong> (<span class="math inline">\(H_{1}\)</span>) : The population variances between the groups are different.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Levene Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: left;">F value</th>
<th style="text-align: left;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">5</td>
<td style="text-align: left;">0.33924778365995</td>
<td style="text-align: left;">0.88821348003483</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">118</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We found that our F-statistc was 0.8865 and a p-value of 0.5433. Since the p-value is greater than the significance level of 0.05 we fail to reject the null hypothesis. This suggests that the variances in Activity Preferences across the groups are not signficantly different. Therefore our assumption of homogeneity of variances is satisfied.</p>
<p>We then conducted the ANOVA Test to determine whether there are any significant differences in the mean proportions of student Activity Proportion and their respective majors.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Anova</caption>
<colgroup>
<col style="width: 15%">
<col style="width: 6%">
<col style="width: 13%">
<col style="width: 12%">
<col style="width: 27%">
<col style="width: 25%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: right;">Sum.Sq</th>
<th style="text-align: right;">Mean.Sq</th>
<th style="text-align: left;">F.value</th>
<th style="text-align: left;">Pr..F.</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">major</td>
<td style="text-align: right;">5</td>
<td style="text-align: right;">11.3293</td>
<td style="text-align: right;">2.26586</td>
<td style="text-align: left;">0.804024073303128</td>
<td style="text-align: left;">0.54898078588717</td>
</tr>
<tr class="even">
<td style="text-align: left;">Residuals</td>
<td style="text-align: right;">118</td>
<td style="text-align: right;">332.5417</td>
<td style="text-align: right;">2.81815</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the ANOVA Analysis we can see that the F-statistic was 0.8040 and a p-value of 0.5940. Since our p-value is greater than α = 0.05 we conclude that the differences in mean activity preferences across majors are not statistically significant meaning that we fail to reject the null hypothesis.</p>
<p>The box plot below is a visual representation of the activity preferences across the different majors. The overlap of the boxes heavily suggests that there is no significant difference in activity Preferences between majors</p>
<div class="cell" data-tbl-cap="Boxplot on Major and Activity Proportion">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/r5-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="testing-for-the-significance-of-gender-on-activity-proportion-using-the-t-test" class="level3" data-number="3.1.2">
<h3 data-number="3.1.2" class="anchored" data-anchor-id="testing-for-the-significance-of-gender-on-activity-proportion-using-the-t-test"><span class="header-section-number">3.1.2</span> Testing for the Significance of Gender on Activity Proportion using the T-Test</h3>
<p>Before we begin with analysis, we must conduct preliminary tests to ensure that we are fit to use this test.</p>
<p>Assumptions of the T-test are:</p>
<p>1. Random Variables: The observations must be independent.(When sampling we took this into account)</p>
<p>2. Normality: The data in each group should be normally distributed.</p>
<p>3.Equality of Variances - The variances in the two groups should be approximately equal. 4. The dependent variable should be measured on an interval or ratio scale.(This has been met as our dependent variable is the proportions of the people in each activity type)</p>
<p><strong><em>Null Hypothesis</em></strong> (<span class="math inline">\(H_{o}\)</span>) : The population means between the groups are equal.</p>
<p><strong><em>Alternative Hypothesis</em></strong> (<span class="math inline">\(H_{1}\)</span>) : The population means between the groups are different.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Shapiro-Wilk Tests</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Gender</th>
<th style="text-align: right;">W Statistic</th>
<th style="text-align: right;">p-value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Males</td>
<td style="text-align: right;">0.8573073</td>
<td style="text-align: right;">3.42e-05</td>
</tr>
<tr class="even">
<td style="text-align: left;">Females</td>
<td style="text-align: right;">0.7645068</td>
<td style="text-align: right;">0.00e+00</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>We conducted the Shapiro-Wilk Test to determine if the distribution in both groups is normal. We were able to determine that both groups were not normal as both their p-values are below the significance level of 0.05. Showing that the normality is not satisfied for both groups.</p>
<p>To test the second Assumption of equality of variances we used the Levene Test.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Levene Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: left;">F value</th>
<th style="text-align: left;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">6.19201670921327</td>
<td style="text-align: left;">0.0141815438250056</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">122</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With an F-statistic of 6.192 which is quite high indicating that there is a big difference between the two groups, we got a p-value of 0.0142 which is less than 0.05 suggesting that the variances in activity preferences between males and females are significantly different.</p>
<p>Since our variances aren’t equal and the normality assumption has also been violated we will conduct our significance test using the Welch t-Test.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>T Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">T_Statistic</th>
<th style="text-align: right;">DF</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: right;">MEAN_FEMALE</th>
<th style="text-align: right;">MEAN_MALE</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">t</td>
<td style="text-align: right;">0.8614468</td>
<td style="text-align: right;">111.3324</td>
<td style="text-align: right;">0.3908436</td>
<td style="text-align: right;">3.125</td>
<td style="text-align: right;">2.868421</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>With a T-statistic of 0.8614, degress of freedom 0f 11.33 and a p-value of 0.3908, we failed to reject the null hypothesis since p-value is greater the significance level of 0.05. This therefore indicates that there is no significant difference in the mean activity preferences between females(mean = 3.125) and males(mean = 2.8684). Therefore Gender doesn’t influence peoples extracurricular choices.</p>
<p>Aside from the overlapping of the boxplots they also have a almost similar medians further showing that there is no significant difference in activity preference between the two genders.</p>
<div class="cell" data-tbl-cap="Boxplot on Gender Identity and Activity Proportion">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/r10-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
<section id="testing-for-the-significance-of-student-status-on-activity-proportion-using-the-t-test" class="level3" data-number="3.1.3">
<h3 data-number="3.1.3" class="anchored" data-anchor-id="testing-for-the-significance-of-student-status-on-activity-proportion-using-the-t-test"><span class="header-section-number">3.1.3</span> Testing for the Significance of Student Status on Activity Proportion using the T-Test</h3>
<p>We conducted preliminary tests before using the test and our results are as shown below.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Shapiro Test on studentStatus</caption>
<thead>
<tr class="header">
<th style="text-align: left;">StudentStatus</th>
<th style="text-align: right;">W_Statistic</th>
<th style="text-align: right;">P_Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">D</td>
<td style="text-align: right;">0.8061721</td>
<td style="text-align: right;">0e+00</td>
</tr>
<tr class="even">
<td style="text-align: left;">I</td>
<td style="text-align: right;">0.7818220</td>
<td style="text-align: right;">1e-07</td>
</tr>
</tbody>
</table>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Levene Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">Df</th>
<th style="text-align: left;">F value</th>
<th style="text-align: left;">Pr(&gt;F)</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">group</td>
<td style="text-align: right;">1</td>
<td style="text-align: left;">0.0108893630670963</td>
<td style="text-align: left;">0.917061284237081</td>
</tr>
<tr class="even">
<td style="text-align: left;"></td>
<td style="text-align: right;">122</td>
<td style="text-align: left;"></td>
<td style="text-align: left;"></td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From our results of the Shapiro-Wilk test we can conclude that our results are not normal.This is because we can see that the p-value of domestic students(0e+00) and international students(1e-07) are both less than α = 0.05 allowing us to reject the null hypothesis.</p>
<p>For an F-value of 0.0109 and a p-value of 0.9171 we were able to conclude that we should reject the fail to reject the null hypothesis. This means that there is no difference in variances of activity preferences between the student status groups.</p>
<p>Since it failed the normality test, we opted to use the Wilcox test as the data isn’t normally distributed.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>T Test</caption>
<thead>
<tr class="header">
<th style="text-align: left;"></th>
<th style="text-align: right;">W Statistic</th>
<th style="text-align: right;">P-Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">W</td>
<td style="text-align: right;">1428.5</td>
<td style="text-align: right;">0.01303</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>From the Wilcox Test of comparing the activity preferences between domestic and international students, with a W-statistic of 1428.5 and a p value of 0.01303 which is below the significance level of 0.05. This shows that there is a significant difference in activity preferences between domestic and international students.</p>
<p>From the boxplot below we can see that the medians between the two are different which validates the result that we got from the Wilcox result. Even though the boxplots are overlapping, there is more spread of activity preferences for international students compared to domestic students.</p>
<div class="cell" data-tbl-cap="Boxplot of Student Status and Activity Proportion">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/r14-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
</section>
</section>
<section id="research-question-2" class="level2" data-number="3.2">
<h2 data-number="3.2" class="anchored" data-anchor-id="research-question-2"><span class="header-section-number">3.2</span> Research Question 2</h2>
<p>In RQ2, we analysed if the proximity to campus affects one’s ability to participate in extracurricular activities.</p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_{o}\)</span>): Proximity to campus (campusDistance) does not affect participation in extracurricular activities.</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_{1}\)</span>): Proximity to campus (campusDistance) has an effect on participation in extracurricular activities.</li>
</ul>
<section id="campus-distance-and-activity-count" class="level3" data-number="3.2.1">
<h3 data-number="3.2.1" class="anchored" data-anchor-id="campus-distance-and-activity-count"><span class="header-section-number">3.2.1</span> Campus Distance and Activity Count</h3>
<p>Statistical Test: To evaluate this, we used the correlation analysis test between campus distance and the number of extracurricular activities using Pearson’s correlation test. Prior to conducting this test, we will verify the assumptions for the test first.</p>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Correlation Analysis</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: right;">CampusDistance</th>
<th style="text-align: right;">ActivityCount</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Min</td>
<td style="text-align: right;">0.000000</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">1st Quartile</td>
<td style="text-align: right;">1.000000</td>
<td style="text-align: right;">0.000000</td>
</tr>
<tr class="odd">
<td style="text-align: left;">Median</td>
<td style="text-align: right;">2.000000</td>
<td style="text-align: right;">1.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Mean</td>
<td style="text-align: right;">2.193548</td>
<td style="text-align: right;">1.451613</td>
</tr>
<tr class="odd">
<td style="text-align: left;">3rd Quartile</td>
<td style="text-align: right;">3.000000</td>
<td style="text-align: right;">2.000000</td>
</tr>
<tr class="even">
<td style="text-align: left;">Max</td>
<td style="text-align: right;">5.000000</td>
<td style="text-align: right;">4.000000</td>
</tr>
</tbody>
</table>
</div>
</div>
<p>The descriptive statistics suggest that most students live fairly close to campus (within 2-3 units) and participate in 1-2 extracurricular activities. This variability in both campusDistance and activityCount supports further analysis to see if there’s a relationship between proximity and participation.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-plot1" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-plot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_report_files/figure-html/fig-plot1-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-plot1-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;1: Scatter Plot
</figcaption>
</figure>
</div>
</div>
</div>
<p>Moving on we inspect the relationship between the variables. As it can be seen from <a href="#fig-plot1" class="quarto-xref">Figure&nbsp;1</a>, there seems to be no linear relation between the variables.</p>
<div class="cell">
<div class="cell-output-display">
<div class="quarto-figure quarto-figure-center">
<figure class="figure">
<p><img src="technical_report_files/figure-html/plot2-1.png" class="img-fluid figure-img" width="672"></p>
<figcaption>Scatter Plot</figcaption>
</figure>
</div>
</div>
</div>
<p>The Q-Q plot displays how the residuals (differences between observed and fitted values) align with the normal distribution. In this case, residuals do not fully align along the red diagonal line, indicating that normality is somewhat violated. The observed points deviate in a stepwise manner, particularly at the tails, which suggests potential non-normality in residuals.</p>
<div class="cell" data-tbl-cap="Scatter Plot">
<div class="cell-output-display">
<div>
<figure class="figure">
<p><img src="technical_report_files/figure-html/plot3-1.png" class="img-fluid figure-img" width="672"></p>
</figure>
</div>
</div>
</div>
<p>This plot helps in identifying any non-linearity, unequal variance (heteroscedasticity), or outliers. Here, residuals seem randomly scattered around the fitted line with no obvious pattern, suggesting homoscedasticity (constant variance). However, a few points like 33, 9, and 15 appear as potential outliers, which might influence the results.</p>
<p>Since there is non-normality between these variables, we proceed with Spearman’s rank correlation to analyze the association between campus distance and activity count.</p>
<div class="cell">
<div id="tbl-plot4" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-plot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;1: Correlation Test Results
</figcaption>
<div aria-describedby="tbl-plot4-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Summary of Correlation Test Results</caption>
<colgroup>
<col style="width: 32%">
<col style="width: 33%">
<col style="width: 11%">
<col style="width: 22%">
</colgroup>
<thead>
<tr class="header">
<th style="text-align: left;">Test</th>
<th style="text-align: right;">Correlation_Coefficient</th>
<th style="text-align: right;">p_value</th>
<th style="text-align: left;">Significance</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Pearson’s Correlation</td>
<td style="text-align: right;">-0.018</td>
<td style="text-align: right;">0.891</td>
<td style="text-align: left;">Not Significant</td>
</tr>
<tr class="even">
<td style="text-align: left;">Spearman’s Correlation</td>
<td style="text-align: right;">0.025</td>
<td style="text-align: right;">0.847</td>
<td style="text-align: left;">Not Significant</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>The Spearman’s rank correlation test results are as follows:</p>
<ul>
<li>Spearman correlation coefficient: 0.025</li>
<li>p-value: 0.847</li>
</ul>
<p>This result indicates a very weak positive correlation between <code>campusDistance</code> and <code>activityCount</code>, but it is not statistically significant (p-value &gt; 0.05). Therefore, we fail to reject the null hypothesis, suggesting no significant association between proximity to campus and participation in extracurricular activities based on this data.</p>
</section>
</section>
<section id="research-question-3" class="level2" data-number="3.3">
<h2 data-number="3.3" class="anchored" data-anchor-id="research-question-3"><span class="header-section-number">3.3</span> Research Question 3</h2>
<p>In RQ3, we analyzed if the the timing, the time spent on extra curricular activity affected one’s level of participation in extracurricular activities.</p>
<ul>
<li>Null Hypothesis (<span class="math inline">\(H_{o}\)</span>): Time Commitment (timeCommitment) does not affect participation levels in extracurricular activities.</li>
<li>Alternative Hypothesis (<span class="math inline">\(H_{1}\)</span>): Time Commitment (timeCommitment) has an effect on participation levels in extracurricular activities.</li>
</ul>
<p>We used the variables of student involvement (studentInvolvement) and activity count (activityCount) to represent the participation levels.</p>
<section id="time-commitment-and-student-involvement" class="level3" data-number="3.3.1">
<h3 data-number="3.3.1" class="anchored" data-anchor-id="time-commitment-and-student-involvement"><span class="header-section-number">3.3.1</span> Time Commitment and Student Involvement</h3>
<p><strong>Statistical Test</strong>: To evaluate this, we used the correlation analysis test between time commitment and student involvement variables using Spearman’s correlation test. Before proceeding with the test, we will verify the assumptions for the test.</p>
<p><strong>Normality of Variables</strong>: In our exploration we found that the variables of timeCommitment (TC), and studentInvolvement (SI) are not normally distributed as seen by the QQ plots in <a href="#fig-normality-of-variables" class="quarto-xref">Figure&nbsp;2</a> as they deviate from the normality line. Hence we proceeded to apply the correlation test using the Spearman’s rank coefficient instead of Pearson’s coefficient (requiring normality).</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normality-of-variables" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normality-of-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_report_files/figure-html/fig-normality-of-variables-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normality-of-variables-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;2: Normality of Variables
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Monotonic Association</strong>: Next we confirmed the assumption of Spearman’s rank coefficient test requiring a monotonic relationship between the variables (timeCommitment and studentInvovlement). We found that the relationship between these variables was monotonic, specifically increasing as seen in <a href="#fig-scatter-plot-involvement" class="quarto-xref">Figure&nbsp;3</a>.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-scatter-plot-involvement" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-scatter-plot-involvement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_report_files/figure-html/fig-scatter-plot-involvement-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-scatter-plot-involvement-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;3: Checking Monotonicity
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Results</strong>: As seen in <a href="#tbl-spear-corr" class="quarto-xref">Table&nbsp;2</a>, the Spearman’s rank correlation coefficient is 0.808, which indicates a strong positive correlation, pointing to a significant monotonic relationship between timeCommitment and studentInvolvement. p-value is &lt; 0.05, hence the correlation is statistically significant, and we can reject the null-hypothesis.</p>
<div class="cell">
<div id="tbl-spear-corr" class="cell quarto-float anchored">
<figure class="quarto-float quarto-float-tbl figure">
<figcaption class="quarto-float-caption-top quarto-float-caption quarto-float-tbl" id="tbl-spear-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Table&nbsp;2: Correlation Test Results
</figcaption>
<div aria-describedby="tbl-spear-corr-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<div class="cell-output-display">
<table class="do-not-create-environment cell table table-sm table-striped small">
<caption>Spearman’s Rank Correlation Results</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Spearman Coefficient (rho)</td>
<td style="text-align: left;">0.744</td>
</tr>
<tr class="even">
<td style="text-align: left;">p-value</td>
<td style="text-align: left;">4.608e-23</td>
</tr>
</tbody>
</table>
</div>
</div>
</figure>
</div>
</div>
<p>Hence students who spend more time in the activities have higher participation in extra curricular activities measured by the activity count, as suggested by the strong association based on our data.</p>
</section>
<section id="time-commitment-and-activity-count" class="level3" data-number="3.3.2">
<h3 data-number="3.3.2" class="anchored" data-anchor-id="time-commitment-and-activity-count"><span class="header-section-number">3.3.2</span> Time Commitment and Activity Count</h3>
<p>We wanted to check whether the time commitment and participation measured by the activityCount variable were correlated.</p>
<p><strong>Statistical Test</strong>:</p>
<p>As discussed before, both the timeCommitment and activityCount variables did not meet normality assumptions, so we proceed with the Spearman’s rank correlation coefficient as our statistical test.</p>
<p><strong>Normality of Variables</strong>:</p>
<p>To proceed with this test, we used QQ-plots to verify normality of timeCommitment (TC) and activityCount(AC). As seen in <a href="#fig-normality-activity" class="quarto-xref">Figure&nbsp;4</a> they are non-normal variables due to their deviation from the normal line.</p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-normality-activity" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-normality-activity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_report_files/figure-html/fig-normality-activity-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-normality-activity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;4: Normality of Variables
</figcaption>
</figure>
</div>
</div>
</div>
<p><strong>Monotonic Association</strong>: We confirmed that the relationship between these variables was monotonic, specifically increasing as seen in <a href="#fig-monotonic-activity" class="quarto-xref">Figure&nbsp;5</a></p>
<div class="cell">
<div class="cell-output-display">
<div id="fig-monotonic-activity" class="quarto-figure quarto-figure-center quarto-float anchored">
<figure class="quarto-float quarto-float-fig figure">
<div aria-describedby="fig-monotonic-activity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
<img src="technical_report_files/figure-html/fig-monotonic-activity-1.png" class="img-fluid figure-img" width="672">
</div>
<figcaption class="quarto-float-caption-bottom quarto-float-caption quarto-float-fig" id="fig-monotonic-activity-caption-0ceaefa1-69ba-4598-a22c-09a6ac19f8ca">
Figure&nbsp;5: Checking Monotonicity
</figcaption>
</figure>
</div>
</div>
</div>
<div class="cell">
<div class="cell-output-display">
<table class="table table-sm table-striped small">
<caption>Correlation Test Results</caption>
<thead>
<tr class="header">
<th style="text-align: left;">Statistic</th>
<th style="text-align: left;">Value</th>
</tr>
</thead>
<tbody>
<tr class="odd">
<td style="text-align: left;">Spearman Coefficient (rho)</td>
<td style="text-align: left;">0.886</td>
</tr>
<tr class="even">
<td style="text-align: left;">p-value</td>
<td style="text-align: left;">1.227e-42</td>
</tr>
</tbody>
</table>
</div>
</div>
<p><strong>Results</strong>: The test results show that the coefficient value is 0.937, indicating a strong positive relationship. This would mean as time commitment increases, so does activity count. The p-value is &lt; 0.05 and indicates strong evidence against the null hypothesis, hence the relationship is unlikely due to chance.</p>
<p>Hence, these results indicate a strong, statistically significant monotonic relationship between time commitment and activity count. As students increase their time commitment, so does their participation measured by involvement.</p>
</section>
</section>
</section>
<section id="sec-data3" class="level1" data-number="4">
<h1 data-number="4"><span class="header-section-number">4</span> Limitations</h1>
<p>This study aimed to understand the reasons why students select and participate in ECAs at UTM. Although our results did not yield significant findings, several limitations may have contributed to this outcome: One such notable limitation is the way in which our data was collected. Although we proposed Stratified Random Sampling to collect our data, we ended up collecting with Simple Random Sampling. This likely lead to higher variance in our analysis and as a result, weaker conclusions. Another big limitation is the possibility of non-response bias in our sampling. Although the survey was distributed in a way that made it available to all students, in effect if certain students we’re choosing not to respond to surveys, their chance of being selected would be zero. In future studies, a better sampling methodology would have been to use StRS with either SRS or Systematic Sampling within the strata. If the study were to be repeated, there would be a number of changes we would like to make in addition to modifying the sampling methodology. We would change the student major question from multiselect to a select one and instruct students to select the major they commit the most time to; this would allow us to streamline and simplify the analysis. The question regarding days of the week could likely be dropped as it proved unbeneficial. This question could be instead replaced with one regarding what time of day students spend most in ECAs. Finally, we would likely change the question regarding students living distance from campus to commute distance. Since the study is interested in what factors affect ECA participation, considering commute distance would be more likely to provide useful information, as two students living the same distance from campus could have vastly different commute times and thus have different amounts of time they can spend on ECAs.</p>
</section>
<section id="conclusion" class="level1" data-number="5">
<h1 data-number="5"><span class="header-section-number">5</span> Conclusion</h1>
<p>This study aims to explore this by investigating the reasons that students select certain extracurricular activities at the University of Toronto Mississauga campus (UTM). Analysis on the preferred types of extracurricular activities whilst also examining whether demographic factors influence these preferences showed that although the most popular type of ECAs amongst students was Athletics and Sports, demographic factors such as gender, student status and program of study. Regarding, the proximity to campus and one’s ability to participate in ECAs, there indicated a very weak positive relationship between the distance from campus and the number of activities that students engage in. Unfortunately, this relationship is not statistically significant. Finally, analysis on the time spent on ECAs indicates that there is a strong statistically significant relationship between time commitment and activity count. Notably, in the future, it would be more beneficial to consider time commuting as a variable of interest than distance from campus. Additionally, modifying the sampling methodology would be an important change if this study were to be repeated by other researchers.</p>
<div style="page-break-after: always;"></div>
</section>
<section id="references" class="level1" data-number="6">
<h1 data-number="6"><span class="header-section-number">6</span> References</h1>
</section>

</main>
<!-- /main column -->
<script id="quarto-html-after-body" type="application/javascript">
window.document.addEventListener("DOMContentLoaded", function (event) {
  const toggleBodyColorMode = (bsSheetEl) => {
    const mode = bsSheetEl.getAttribute("data-mode");
    const bodyEl = window.document.querySelector("body");
    if (mode === "dark") {
      bodyEl.classList.add("quarto-dark");
      bodyEl.classList.remove("quarto-light");
    } else {
      bodyEl.classList.add("quarto-light");
      bodyEl.classList.remove("quarto-dark");
    }
  }
  const toggleBodyColorPrimary = () => {
    const bsSheetEl = window.document.querySelector("link#quarto-bootstrap");
    if (bsSheetEl) {
      toggleBodyColorMode(bsSheetEl);
    }
  }
  toggleBodyColorPrimary();  
  const icon = "";
  const anchorJS = new window.AnchorJS();
  anchorJS.options = {
    placement: 'right',
    icon: icon
  };
  anchorJS.add('.anchored');
  const isCodeAnnotation = (el) => {
    for (const clz of el.classList) {
      if (clz.startsWith('code-annotation-')) {                     
        return true;
      }
    }
    return false;
  }
  const clipboard = new window.ClipboardJS('.code-copy-button', {
    text: function(trigger) {
      const codeEl = trigger.previousElementSibling.cloneNode(true);
      for (const childEl of codeEl.children) {
        if (isCodeAnnotation(childEl)) {
          childEl.remove();
        }
      }
      return codeEl.innerText;
    }
  });
  clipboard.on('success', function(e) {
    // button target
    const button = e.trigger;
    // don't keep focus
    button.blur();
    // flash "checked"
    button.classList.add('code-copy-button-checked');
    var currentTitle = button.getAttribute("title");
    button.setAttribute("title", "Copied!");
    let tooltip;
    if (window.bootstrap) {
      button.setAttribute("data-bs-toggle", "tooltip");
      button.setAttribute("data-bs-placement", "left");
      button.setAttribute("data-bs-title", "Copied!");
      tooltip = new bootstrap.Tooltip(button, 
        { trigger: "manual", 
          customClass: "code-copy-button-tooltip",
          offset: [0, -8]});
      tooltip.show();    
    }
    setTimeout(function() {
      if (tooltip) {
        tooltip.hide();
        button.removeAttribute("data-bs-title");
        button.removeAttribute("data-bs-toggle");
        button.removeAttribute("data-bs-placement");
      }
      button.setAttribute("title", currentTitle);
      button.classList.remove('code-copy-button-checked');
    }, 1000);
    // clear code selection
    e.clearSelection();
  });
    var localhostRegex = new RegExp(/^(?:http|https):\/\/localhost\:?[0-9]*\//);
    var mailtoRegex = new RegExp(/^mailto:/);
      var filterRegex = new RegExp('/' + window.location.host + '/');
    var isInternal = (href) => {
        return filterRegex.test(href) || localhostRegex.test(href) || mailtoRegex.test(href);
    }
    // Inspect non-navigation links and adorn them if external
 	var links = window.document.querySelectorAll('a[href]:not(.nav-link):not(.navbar-brand):not(.toc-action):not(.sidebar-link):not(.sidebar-item-toggle):not(.pagination-link):not(.no-external):not([aria-hidden]):not(.dropdown-item):not(.quarto-navigation-tool)');
    for (var i=0; i<links.length; i++) {
      const link = links[i];
      if (!isInternal(link.href)) {
        // undo the damage that might have been done by quarto-nav.js in the case of
        // links that we want to consider external
        if (link.dataset.originalHref !== undefined) {
          link.href = link.dataset.originalHref;
        }
      }
    }
  function tippyHover(el, contentFn, onTriggerFn, onUntriggerFn) {
    const config = {
      allowHTML: true,
      maxWidth: 500,
      delay: 100,
      arrow: false,
      appendTo: function(el) {
          return el.parentElement;
      },
      interactive: true,
      interactiveBorder: 10,
      theme: 'quarto',
      placement: 'bottom-start',
    };
    if (contentFn) {
      config.content = contentFn;
    }
    if (onTriggerFn) {
      config.onTrigger = onTriggerFn;
    }
    if (onUntriggerFn) {
      config.onUntrigger = onUntriggerFn;
    }
    window.tippy(el, config); 
  }
  const noterefs = window.document.querySelectorAll('a[role="doc-noteref"]');
  for (var i=0; i<noterefs.length; i++) {
    const ref = noterefs[i];
    tippyHover(ref, function() {
      // use id or data attribute instead here
      let href = ref.getAttribute('data-footnote-href') || ref.getAttribute('href');
      try { href = new URL(href).hash; } catch {}
      const id = href.replace(/^#\/?/, "");
      const note = window.document.getElementById(id);
      if (note) {
        return note.innerHTML;
      } else {
        return "";
      }
    });
  }
  const xrefs = window.document.querySelectorAll('a.quarto-xref');
  const processXRef = (id, note) => {
    // Strip column container classes
    const stripColumnClz = (el) => {
      el.classList.remove("page-full", "page-columns");
      if (el.children) {
        for (const child of el.children) {
          stripColumnClz(child);
        }
      }
    }
    stripColumnClz(note)
    if (id === null || id.startsWith('sec-')) {
      // Special case sections, only their first couple elements
      const container = document.createElement("div");
      if (note.children && note.children.length > 2) {
        container.appendChild(note.children[0].cloneNode(true));
        for (let i = 1; i < note.children.length; i++) {
          const child = note.children[i];
          if (child.tagName === "P" && child.innerText === "") {
            continue;
          } else {
            container.appendChild(child.cloneNode(true));
            break;
          }
        }
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(container);
        }
        return container.innerHTML
      } else {
        if (window.Quarto?.typesetMath) {
          window.Quarto.typesetMath(note);
        }
        return note.innerHTML;
      }
    } else {
      // Remove any anchor links if they are present
      const anchorLink = note.querySelector('a.anchorjs-link');
      if (anchorLink) {
        anchorLink.remove();
      }
      if (window.Quarto?.typesetMath) {
        window.Quarto.typesetMath(note);
      }
      // TODO in 1.5, we should make sure this works without a callout special case
      if (note.classList.contains("callout")) {
        return note.outerHTML;
      } else {
        return note.innerHTML;
      }
    }
  }
  for (var i=0; i<xrefs.length; i++) {
    const xref = xrefs[i];
    tippyHover(xref, undefined, function(instance) {
      instance.disable();
      let url = xref.getAttribute('href');
      let hash = undefined; 
      if (url.startsWith('#')) {
        hash = url;
      } else {
        try { hash = new URL(url).hash; } catch {}
      }
      if (hash) {
        const id = hash.replace(/^#\/?/, "");
        const note = window.document.getElementById(id);
        if (note !== null) {
          try {
            const html = processXRef(id, note.cloneNode(true));
            instance.setContent(html);
          } finally {
            instance.enable();
            instance.show();
          }
        } else {
          // See if we can fetch this
          fetch(url.split('#')[0])
          .then(res => res.text())
          .then(html => {
            const parser = new DOMParser();
            const htmlDoc = parser.parseFromString(html, "text/html");
            const note = htmlDoc.getElementById(id);
            if (note !== null) {
              const html = processXRef(id, note);
              instance.setContent(html);
            } 
          }).finally(() => {
            instance.enable();
            instance.show();
          });
        }
      } else {
        // See if we can fetch a full url (with no hash to target)
        // This is a special case and we should probably do some content thinning / targeting
        fetch(url)
        .then(res => res.text())
        .then(html => {
          const parser = new DOMParser();
          const htmlDoc = parser.parseFromString(html, "text/html");
          const note = htmlDoc.querySelector('main.content');
          if (note !== null) {
            // This should only happen for chapter cross references
            // (since there is no id in the URL)
            // remove the first header
            if (note.children.length > 0 && note.children[0].tagName === "HEADER") {
              note.children[0].remove();
            }
            const html = processXRef(null, note);
            instance.setContent(html);
          } 
        }).finally(() => {
          instance.enable();
          instance.show();
        });
      }
    }, function(instance) {
    });
  }
      let selectedAnnoteEl;
      const selectorForAnnotation = ( cell, annotation) => {
        let cellAttr = 'data-code-cell="' + cell + '"';
        let lineAttr = 'data-code-annotation="' +  annotation + '"';
        const selector = 'span[' + cellAttr + '][' + lineAttr + ']';
        return selector;
      }
      const selectCodeLines = (annoteEl) => {
        const doc = window.document;
        const targetCell = annoteEl.getAttribute("data-target-cell");
        const targetAnnotation = annoteEl.getAttribute("data-target-annotation");
        const annoteSpan = window.document.querySelector(selectorForAnnotation(targetCell, targetAnnotation));
        const lines = annoteSpan.getAttribute("data-code-lines").split(",");
        const lineIds = lines.map((line) => {
          return targetCell + "-" + line;
        })
        let top = null;
        let height = null;
        let parent = null;
        if (lineIds.length > 0) {
            //compute the position of the single el (top and bottom and make a div)
            const el = window.document.getElementById(lineIds[0]);
            top = el.offsetTop;
            height = el.offsetHeight;
            parent = el.parentElement.parentElement;
          if (lineIds.length > 1) {
            const lastEl = window.document.getElementById(lineIds[lineIds.length - 1]);
            const bottom = lastEl.offsetTop + lastEl.offsetHeight;
            height = bottom - top;
          }
          if (top !== null && height !== null && parent !== null) {
            // cook up a div (if necessary) and position it 
            let div = window.document.getElementById("code-annotation-line-highlight");
            if (div === null) {
              div = window.document.createElement("div");
              div.setAttribute("id", "code-annotation-line-highlight");
              div.style.position = 'absolute';
              parent.appendChild(div);
            }
            div.style.top = top - 2 + "px";
            div.style.height = height + 4 + "px";
            div.style.left = 0;
            let gutterDiv = window.document.getElementById("code-annotation-line-highlight-gutter");
            if (gutterDiv === null) {
              gutterDiv = window.document.createElement("div");
              gutterDiv.setAttribute("id", "code-annotation-line-highlight-gutter");
              gutterDiv.style.position = 'absolute';
              const codeCell = window.document.getElementById(targetCell);
              const gutter = codeCell.querySelector('.code-annotation-gutter');
              gutter.appendChild(gutterDiv);
            }
            gutterDiv.style.top = top - 2 + "px";
            gutterDiv.style.height = height + 4 + "px";
          }
          selectedAnnoteEl = annoteEl;
        }
      };
      const unselectCodeLines = () => {
        const elementsIds = ["code-annotation-line-highlight", "code-annotation-line-highlight-gutter"];
        elementsIds.forEach((elId) => {
          const div = window.document.getElementById(elId);
          if (div) {
            div.remove();
          }
        });
        selectedAnnoteEl = undefined;
      };
        // Handle positioning of the toggle
    window.addEventListener(
      "resize",
      throttle(() => {
        elRect = undefined;
        if (selectedAnnoteEl) {
          selectCodeLines(selectedAnnoteEl);
        }
      }, 10)
    );
    function throttle(fn, ms) {
    let throttle = false;
    let timer;
      return (...args) => {
        if(!throttle) { // first call gets through
            fn.apply(this, args);
            throttle = true;
        } else { // all the others get throttled
            if(timer) clearTimeout(timer); // cancel #2
            timer = setTimeout(() => {
              fn.apply(this, args);
              timer = throttle = false;
            }, ms);
        }
      };
    }
      // Attach click handler to the DT
      const annoteDls = window.document.querySelectorAll('dt[data-target-cell]');
      for (const annoteDlNode of annoteDls) {
        annoteDlNode.addEventListener('click', (event) => {
          const clickedEl = event.target;
          if (clickedEl !== selectedAnnoteEl) {
            unselectCodeLines();
            const activeEl = window.document.querySelector('dt[data-target-cell].code-annotation-active');
            if (activeEl) {
              activeEl.classList.remove('code-annotation-active');
            }
            selectCodeLines(clickedEl);
            clickedEl.classList.add('code-annotation-active');
          } else {
            // Unselect the line
            unselectCodeLines();
            clickedEl.classList.remove('code-annotation-active');
          }
        });
      }
  const findCites = (el) => {
    const parentEl = el.parentElement;
    if (parentEl) {
      const cites = parentEl.dataset.cites;
      if (cites) {
        return {
          el,
          cites: cites.split(' ')
        };
      } else {
        return findCites(el.parentElement)
      }
    } else {
      return undefined;
    }
  };
  var bibliorefs = window.document.querySelectorAll('a[role="doc-biblioref"]');
  for (var i=0; i<bibliorefs.length; i++) {
    const ref = bibliorefs[i];
    const citeInfo = findCites(ref);
    if (citeInfo) {
      tippyHover(citeInfo.el, function() {
        var popup = window.document.createElement('div');
        citeInfo.cites.forEach(function(cite) {
          var citeDiv = window.document.createElement('div');
          citeDiv.classList.add('hanging-indent');
          citeDiv.classList.add('csl-entry');
          var biblioDiv = window.document.getElementById('ref-' + cite);
          if (biblioDiv) {
            citeDiv.innerHTML = biblioDiv.innerHTML;
          }
          popup.appendChild(citeDiv);
        });
        return popup.innerHTML;
      });
    }
  }
});
</script>
</div> <!-- /content -->




</body></html>